language: node_js
install:
- npm install -g dockerlint
script:
- dockerlint
- make build=edge
before_deploy:
- docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
deploy:
- provider: script
  script: docker push amancevice/superset:edge
  on:
    repo: amancevice/docker-superset
