language: node_js
env:
- TARGET=edge
- TARGET=latest
install:
- npm install -g dockerlint
script:
- dockerlint
- make $TARGET
before_deploy:
- docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
deploy:
- provider: script
  script: docker push amancevice/superset:edge
  on:
    repo: amancevice/docker-superset
    branch: master
    condition: ${TARGET} = edge
- provider: script
  script: make push
  on:
    repo: amancevice/docker-superset
    tags: true
