language: node_js
install:
- npm install -g dockerlint
script:
- dockerlint
- make
before_deploy:
- docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
deploy:
- provider: script
  script: make push
  on:
    tags: true
    repo: amancevice/docker-superset
