version: '3'
services:
  superset:
    build:
      context: .
      args:
        SUPERSET_VERSION: ${SUPERSET_VERSION:-0.29.0rc7}
    image: amancevice/superset:${SUPERSET_VERSION:-latest}
    ports:
      - 8088:8088
