name: edge
on:
  push:
  schedule:
    - cron: "11 21 * * *"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g dockerlint
      - run: dockerlint
  build-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - run: pip install pipenv
      - run: make edge
      - run: make push
