name: latest

on:
  pull_request:
  push:
    branches:
    - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install -g dockerlint
      - run: dockerlint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v1
    - run: make latest clobber
