name: push
on:
  release:
    types:
      - published
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g dockerlint
      - run: dockerlint
  build-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: meta
        id: meta
        run: |
          version="$(grep apache-superset Pipfile | grep -Eo '[0-9.]+')"
          tags="amancevice/superset,amancevice/superset:$version"
          echo "tags=$tags" >> "$GITHUB_OUTPUT"
      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
