name: push

on:
  release:
    types:
    - published

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install -g dockerlint
      - run: dockerlint

  build-push:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: make latest clean
    - run: docker push amancevice/superset
    - run: make clobber
